version: '3.8'

services:
  health-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-progress-tracker
    ports:
      - "3000:3000"
    volumes:
      # Persist database data
      - health-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http=require('http'); http.get('http://localhost:3000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  health-data:
    driver: local